### ISSUE TITLE
ORM vs pure SQL

### ISSUE THREAD

**Issue by dzahariev** [Peripli/service-manager#4]
Research different SQL packages: jinzhu/gorm, database/sql, jmoiron/sqlx, others? 
Describe benefits and advantages from one side and disadvantages from the other side on the different approaches.

-----
The deliverable for research task is a comprehensive comment inside the issue that provide valuable information about the researched topic. It will be very helpful to be organised a knowledge sharing session with the team on the topic, that explains the matter and provide some examples. The issue can be closed once the team agrees on the technology that shall be used for each one specific aspect.

**Comment by NickyMateev** [comment]
# ORM vs Pure SQL
For the initial implementation of the **Service Manager** a pure SQL communication with the database will be used. With the help of the [`database/sql`][1] standard package as well as a third-party library called [`sqlx`][2].

## `database/sql`
The standard package provides us with a number of essential functionalities like:
 * querying
 * prepared statements
 * transactions
 * concurrent access to DB
 * connection pooling

## `sqlx`
 [`sqlx`][2] is not an ORM. It's a library which extends the standard [`database/sql`][1] package and provides the following useful features:
* Marshal rows into structs (with embedded struct support), maps, and slices
* Named parameter support including prepared statements
* `Get` and `Select` to go quickly from query to struct/slice

## Postgres driver for Go - `pq`
Since we'll be using a Postgres database for persistence a driver will be needed. [`pq`][3] seems to be the most widely used option.

[SQL database drivers (via Official Golang Wiki)][4]

## What about ORMs?
ORMs definitely make the developer's job easier, but performance will be lost and they can also cause headaches on things like complex joins. With our current database model, we've decided that it won't be that much of a hassle to write SQL manually.

Some widely known Go ORMs:
* [gorm][5]
* [reform][6]
* [go-queryset][7]
* [gorp][8]

[1]: https://golang.org/pkg/database/sql/
[2]: https://github.com/jmoiron/sqlx
[3]: https://github.com/lib/pq
[4]: https://github.com/golang/go/wiki/SQLDrivers
[5]: https://github.com/jinzhu/gorm
[6]: https://github.com/go-reform/reform
[7]: https://github.com/jirfag/go-queryset
[8]: https://github.com/go-gorp/gorp
