### ISSUE TITLE
Dependency management options

### ISSUE THREAD

**Issue by dzahariev** [Peripli/service-manager#7]
Research and compare godep vs dep, vs glide or others?
Come up with final proposal that shall be used.

-----
The deliverable for research task is a comprehensive comment inside the issue that provide valuable information about the researched topic. It will be very helpful to be organised a knowledge sharing session with the team on the topic, that explains the matter and provide some examples. The issue can be closed once the team agrees on the technology that shall be used for each one specific aspect.

**Comment by NickyMateev** [comment]
# Dependency management options

Efficient dependency management is paramount for every successful project. In the Go Community there's only one solution, which has proven to be safe and stable - [dep][1].

## Dep
`dep` is a dependency management tool for Go. It requires **Go 1.9** or newer to compile and is **safe for production use**. The tool is currently in the process of becoming the official Go tool for managing dependencies.

`dep` provides us with the following functionalities:
* automated ability to determine all of a project's dependencies
* identify the latest version of a package that satisfies all dependencies in the dependency graph
* ability to specify a range of acceptable versions of packages that satisfy the project's dependencies
* ability to pin the range of acceptable versions to a set of explicit versions used for reproducible builds
* ability to prune any unnecessary packages from the resulting vendor set

## Other dependency management tools
`godep` and `glide` are probably the next well known dependency management tools in the Go Community but production for each of them has stopped and both reference `dep` as the way to *go*.

[1]: https://github.com/golang/dep

**Comment by georgethebeatle** [comment]
# BTP Operator

We managed to [deploy our own](https://github.tools.sap/neoCoreArchitecture/trinity/commit/763c07c561e5b97dd3cca1069f72b2335192b552) hacked btp operator and made it [pass the `cloudfoudry` environment](https://github.tools.sap/neoCoreArchitecture/trinity-btp-service-operator/commit/af7123cd71a237fede1d5da32f1a419cddb43547) when querying the service-manager for offerings and plans.

As a result we were able to see the `postgresql-db` offering and its `development` plan, but when we created a serviceinstance resource we observed the following error condition it its status:

```
apiVersion: v1
items:
- apiVersion: services.cloud.sap.com/v1
  kind: ServiceInstance
  spec:
    ...
  status:
    conditions:
    - lastTransitionTime: "2023-03-10T10:43:08Z"
      message: |
        request POST https://service-manager.cfapps.eu10.hana.ondemand.com/v1/service_instances failed: StatusCode: 404 Body: {"error":"NotFound","description":"could not find such service plan"}

```

It looked like the btp operator was sending the `cloudfoudry` environment parameter to the service-manager correctly, but the service manager was dropping it on the floor and was not seeing the `development` plan itself.

# Service Manager

We managed to replicate the requests that the btp operator is making to the service-manager using the `smctl` and did get the same errors that the btp operator was getting. We were then able to find the places in the service-manager sources that produces these errors.

## Create service instance

### By offering name and plan name

```
❯ smctl curl "/v1/service_instances" --param async=true -X POST -d '{
  "name": "my-service-instance",
  "service_offering_name": "postgresql-db",
  "service_plan_name": "development"
}'
Error: request POST https://service-manager.cfapps.eu10.hana.ondemand.com/v1/service_instances?async=true failed: StatusCode: 400 Body: {"error":"BadRequest","description":"service plan development not found for service offering postgresql-db"}

```
Here is the origin of this [Bad Request](https://github.com/Peripli/service-manager/blob/41e0c0fa825797e09a71d9712161eed1453aea7f/api/filters/extract_plan_id_by_service_and_plan_name_filter.go#L79-L82) error

This is the [query to the database](https://github.com/Peripli/service-manager/blob/41e0c0fa825797e09a71d9712161eed1453aea7f/api/filters/extract_plan_id_by_service_and_plan_name_filter.go#L68-L74) that lists service instances by offering and plan names

This is the uderlying [SQL query](https://github.com/Peripli/service-manager/blob/41e0c0fa825797e09a71d9712161eed1453aea7f/storage/named_query.go#L74-L86).

### By plan id

```
❯ smctl curl "/v1/service_instances?async=true" -X POST -d '{
  "service_plan_id": "4d6e27f5-a5b3-4c88-b012-663f14ce93ea"
}'
Error: request POST https://service-manager.cfapps.eu10.hana.ondemand.com/v1/service_instances?async=true failed: StatusCode: 404 Body: {"error":"NotFound","description":"could not find such service plan"}
```
Here is the origin of this [NotFound](https://github.com/Peripli/service-manager/blob/41e0c0fa825797e09a71d9712161eed1453aea7f/api/filters/check_instance_visibility_filter.go#L88-L92) error

This is the [query to the database](https://github.com/Peripli/service-manager/blob/41e0c0fa825797e09a71d9712161eed1453aea7f/api/filters/check_instance_visibility_filter.go#L73-L78)

This is the underlying [SQL query](https://github.com/Peripli/service-manager/blob/41e0c0fa825797e09a71d9712161eed1453aea7f/storage/named_query.go#L67-L73)

# Conclusion

It looks like in both cases the service instance results are being filtered out by their platform visibility as it is persisted in the database. The desired platform in both cases above is [hardcoded](https://github.com/Peripli/service-manager/blob/41e0c0fa825797e09a71d9712161eed1453aea7f/pkg/sm/sm.go#L670) to [`service-manager`
(https://github.com/Peripli/service-manager/blob/41e0c0fa825797e09a71d9712161eed1453aea7f/pkg/types/platform.go#L32) - it is neither `cloudfoudry` nor `kubernetes` and this cannot be configured.

###

It looks like there are two ways forward:
- Ask the service-manager team to provide us with a hacked deployment of the service manager that will disable this visibility filtering or will set its default platform to `cloudfoudry` rather than `service-manager`
- Try to provision a hana instance and deploy the MTA against hana
